### ISSUE TITLE
 pkg_resources.DistributionNotFound: gevent>=1.0

### ISSUE THREAD

**Issue by thejmill** [neal/WeMote#1]
I'm trying to run Ouimeaux and WeMote server on a windows 7 machine and I've installed python 3.3 with event and greenlet as well as ouimeaux.  When I run a command for wemote server in a windows cmd prompt I get the following error.

Any help would be appreciated.

c:\Python33\Scripts>wemo server
Traceback (most recent call last):
  File "c:\Python33\Scripts\wemo-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Python33\lib\site-packages\setuptools-2.2-py3.3.egg\pkg_resources.py"
, line 2716, in <module>
  File "C:\Python33\lib\site-packages\setuptools-2.2-py3.3.egg\pkg_resources.py"
, line 685, in require
  File "C:\Python33\lib\site-packages\setuptools-2.2-py3.3.egg\pkg_resources.py"
, line 588, in resolve
pkg_resources.DistributionNotFound: gevent>=1.0

**Comment by neal** [comment]
This issue belongs at https://github.com/iancmcc/ouimeaux instead.
